spring:
  application:
    name: data-jpa

  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#        show_sql: true -> System.out 으로 로그를 남기는 것

logging.level:
  org.hibernate.SQL: debug # logger 로 로그로 남기는 것


